version: 2

models:
  - name: product_performance
    description: "Product performance metrics across different categories."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
        tests:
          - not_null
          - unique
      - name: product_name
        description: "Name of the product."
        tests:
          - not_null
      - name: category
        description: "Category of the product."
        tests:
          - not_null
      - name: total_units_sold
        description: "Total number of units sold."
        tests:
          - not_null
      - name: total_sales_amount
        description: "Total sales amount."
        tests:
          - not_null
      - name: average_selling_price
        description: "Average selling price of the product."
        tests:
          - not_null
      - name: total_returns
        description: "Total number of returns."
        tests:
          - not_null
      - name: first_purchase_date
        description: "Date of the first purchase."
        tests:
          - not_null
      - name: recent_purchase_date
        description: "Date of the most recent purchase."
        tests:
          - not_null
